version: '3.3'

services:

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432 # For debugging only
    environment:
      POSTGRES_USER: raphael
      POSTGRES_PASSWORD: raphael-password # For debugging only, change in production!!!

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: dracula

volumes:
  db_data: {}